version: "3.9"

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "4443:443"
    depends_on:
      - wordpress
